core/urls.py
from django.urls import path, include
from . import views 


app_name ='core'
urlpatterns = [
    
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name="contact"),
        path('about-us/', views.AboutView.as_view(), name="about"),
    path('contact/success/', views.ContactSuccessView.as_view(), name='contact-success'),
    path('shop/', views.ShopView.as_view(), name="shop"),
    path('product/<slug>', views.DetailView.as_view(), name="details" ),
    # path('cart/', views.CartView.as_view(), name="cart" ),
    # path('checkout/', views.CheckoutView.as_view(), name="checkout" ),
          path('wishlist/<slug>/', views.wishlist, name="wishlist"),
      path('wishlist/home/<slug>/', views.wishlist_home, name="wishlist-home"),
      path('add_to_cart/<slug>', views.add_to_cart, name='add-to-cart'),
    #    path('pricing/', views.PricingView.as_view(), name="pricing" ),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/',  views.remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
  path('wishlist/product/<slug>/', views.wishlist_product, name='wishlist-product'),
  path('cart/', views.CartView.as_view(), name='cart'),
   path('checkout/', views.CheckoutView.as_view(), name="checkout" ),
path('payment/receipt/', views.PaystackView.as_view(), name="payment" ),
      path('payment/success/', views.ConfirmView.as_view(), name="pay" ),
        path('payment/failed/', views.FailedView.as_view(), name="pay-failed" ),
         path('search/', views.SearchListView.as_view(), name="search" ),
          path('category/<slug>/', views.CategoryView, name='categoryview'),
]

paystack/urls.py
from . import views
from . import settings
from django.views.decorators.csrf import csrf_exempt
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url


urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

stroyal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500


urlpatterns = [
     path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
        path("paystack", include(('paystack.urls','paystack'),namespace='paystack')),

]


handler404 = "core.views.handler404"

urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

templates/alert.html
{% if messages %}
<section class="alerts messages">
	<div class="container">
	
		<div class="row mt-30">
	
			{% for message in messages %}
			<div {% if message.tags %}  class="alert col-md-12 {{ message.tags }} alert-common alert-dismissible" {% endif %} role="alert">
			
			 {{ message }}
			</div>
	
			{% endfor %}
			
		</div>
	</div>
</section>
{% endif %}

templates/base.html
{% load static %}
<!doctype html>
<html>

<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-178514552-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-178514552-1');
</script>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'img//apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ff0000">
<meta name="msapplication-TileImage" content="{% static 'img/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ff0000">
{% block css %}
{% endblock css %}
    <div id="back-top" >
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- flaticon CSS -->


    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
        <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>


{% include 'navbar.html' %}

{% include 'alert.html' %}


{% block content %}
{% endblock content %}

    {% include 'footer.html' %}

    {% comment %} <!-- jquery plugins here-->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/masonry.pkgd.js' %}"></script>
    <!-- particles js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- slick js -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>

    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js' %}"></script>
      <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script> {% endcomment %}

        <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- easing js -->
  <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
  <!-- swiper js -->
  <script src="{% static 'js/lightslider.min.js' %}"></script>
  <!-- swiper js -->
  <script src="{% static 'js/masonry.pkgd.js' %}"></script>
  <!-- particles js -->
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
  <!-- slick js -->
  <script src="{% static 'js/slick.min.js' %}"></script>
  <script src="{% static 'js/swiper.jquery.js' %}"></script>
  <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
  <script src="{% static 'js/waypoints.min.js' %}"></script>
  <script src="{% static 'js/contact.js' %}"></script>
  <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
  <script src="{% static 'js/jquery.form.js' %}"></script>
  <script src="{% static 'js/jquery.validate.min.js' %}"></script>
  <script src="{% static 'js/mail-script.js' %}"></script>
  <script src="{% static 'js/stellar.js' %}"></script>
  <!-- custom js -->
  <script src="{% static 'js/theme.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

templates/category.html
{% extends 'base.html' %} {% load thumbnail %} {% load static %} {% block css %}
{% load humanize %}
<title>{{category.name|title}} Category - St Royal Stoi</title>
{% endblock css %} {% block content %}
<!--================Home Banner Area =================-->
<!-- breadcrumb start-->
<section class="breadcrumb breadcrumb_bg">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="breadcrumb_iner">
          <div class="breadcrumb_iner_item">
            <h2>{{category.name|title}} Category</h2>
            <p>Home <span>-</span> {{category.name|title}} Category</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- breadcrumb start-->
<section class="page-add mt-3">
    <div class="container">
      <div class="row">
        {% for item in shoptop %}
        <div class="col-lg-6 col-sm-6 mt-2">
          <img src="{{item.image.url}}" alt="" />
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
<!--================Category Product Area =================-->
<section class="cat_product_area section_padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <div class="row">
          <div class="col-lg-12">
            <div
              class="product_top_bar d-flex justify-content-between align-items-center"
            >
              <div class="single_product_menu">
                <p><span class="text-red">Products </span> Listed</p>
              </div>
            </div>
          </div>
        </div>

        <div class="row align-items-center latest_product_inner">
          {% for item in instance %}
          <div class="col-lg-4 col-sm-6">
            <div class="single_product_item">
              {% thumbnail item.image '250x250' crop='center' as stoi %}
              <img
                src="{{stoi.url}}"
                height="{{stoi.height}}"
                width="{{stoi.width}}"
                alt="St Royal Stoi's {{item.title|title}}"
              />
              {% endthumbnail %}
              <div class="single_product_text">
                <h4>{{item.title|title}}</h4>
                <h3>&#8358; {{item.price|intcomma}}</h3>
                <a href="{{item.get_absolute_url}}" class="btn_3">View Item</a>
              </div>
            </div>
          </div>
          {% empty %}
          <div class="col-lg-12 text-center">
            <h2>No items in this {{category.name|title}} category</h2>
          </div>

          {% endfor %}

          <div class="col-lg-12">
            {% if instance.has_other_pages %}
            <div class="pageination">
              <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                  {% if instance.has_previous %}
                  <li class="page-item">
                    <a
                      class="page-link"
                      href="?page={{instance.previous_page_number}}"
                      aria-label="Previous"
                    >
                      <i class="ti-angle-double-left"></i>
                    </a>
                  </li>

                  <li class="page-item">
                    <a
                      class="page-link"
                      href="?page={{pinstance.previous_page_number}}"
                      >{{page_obj.previous_page_number}}</a
                    >
                  </li>

                  {% endif %}

                  <li class="page-item">
                    <a class="page-link" href="?page={{instance.number}}"
                      >{{instance.number}}</a
                    >
                  </li>

                  {% if instance.has_next %}
                  <li class="page-item">
                    <a
                      class="page-link"
                      href="?page={{instance.next_page_number}}"
                      >{{instance.next_page_number}}</a
                    >
                  </li>

                  <li class="page-item">
                    <a
                      class="page-link"
                      href="?page={{instance.next_page_number}}"
                      aria-label="Next"
                    >
                      <i class="ti-angle-double-right"></i>
                    </a>
                  </li>
                  {% endif %}
                </ul>
              </nav>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col-lg-3">
        <div class="left_sidebar_area">
          <aside class="left_widgets p_filter_widgets">
            <div class="l_w_title">
              <h3>Categories</h3>
            </div>
            <div class="widgets_inner">
              <ul class="list">
                {% for item in categories %}
                <li>
                  <a href="{{ item.get_category_url }}"
                    >{{ item.name|title }}</a
                  >
                  <span>({{item.get_category_count}})</span>
                </li>
                {% endfor %}
              </ul>
            </div>
            {% for item in shopside %}
            <div class="watch-area">
              <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="choice-watch-img mb-40">
                  <img src="{{item.image.url}}" alt="" />
                </div>
              </div>
            </div>
            {% endfor %}
          </aside>
        </div>
      </div>
    </div>
  </div>
</section>

<!--================End Category Product Area =================-->

<!-- product_list part start-->

<!-- product_list part end-->
{% endblock content %}

templates/confirmation.html
{% extends 'base.html' %}
{% load humanize %}
{% block css %}
{% load paystack %}

<title>Order Confirmation - St Royal Stoi </title>
{% endblock css %}


{% block content %}  <!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2>Order Confirmation</h2>
              <p>Home <span>-</span> Order Confirmation</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- breadcrumb start-->

  <!--================ confirmation part start =================-->
  <section class="confirmation_part padding_top">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="confirmation_tittle">
            <h2>Thank you. </h2>
            <h2>We have received your order <br> <span class="text-red">We will contact you shortly</span></h2>
          </div>
        </div>

      
      
      </div>
      <div class="row">
        <div class="col-lg-12">
    
            </table>
            <div class="text-center m-t-30">	
          
<a href="{% url 'core:shop' %}" class="btn_3">Continue Shopping</a>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================ confirmation part end =================-->
{% endblock content %}

templates/footer.html
    <!--::footer_part start::-->

    {% load static %}
 <footer class="footer_part">
        <div class="container">
            <div class="row justify-content-around">
                <div class="col-sm-6 col-lg-4">
                    <div class="single_footer_part d-flex flex-column align-items-start">
                    		<div class="footer__logo">
                        <a href="{% url 'core:home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                    <p>We work with a team to create profitable customers and provide you with the best and happiest materials.</p>
                    	<p class="sm-head">
									<span class="fa fa-location-arrow"></span>
									Head Office
								</p>
								<p>F-LINE F1930 Alaba International market ojo L.G.A Lagos Ojo 108105
                                    Lagos <br>
                                    Nigeria</p>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4">
                    <div class="single_footer_part d-flex flex-column align-items-start">
                        <h4>Quick Links</h4>
                        <ul class="list-unstyled">
                            <li><a href="{% url 'core:home' %}">Home</a></li>
                            <li><a href="{% url 'core:about' %}">About Us</a></li>
                            <li><a href="{% url 'core:shop' %}">Shop</a></li>
                            <li><a href="{% url 'core:contact' %}">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
      
                <div class="col-sm-6 text-left  col-lg-4">
               				<div class="single_footer_part d-flex flex-column align-items-start">
							<h4 class="footer_title">Contact Us</h4>
						
                        
	
								<p class="sm-head">
								
								</p>
								<p>
									<span class="fa fa-phone mr-1"></span> <a href="tel:+2348184120039">+234818 412 0039</a>
                            <br>
                            <span class="fa fa-phone mr-1"></span> <a href="tel:+2348055803354">+234 805 580 3354</a>
							
								</p>
	
								<p class="sm-head">
									
									
								</p>
								<p>
<span class="fa fa-envelope mr-1"></span> <a href="mailto:admin@stroyalstoi.com">admin@stroyalstoi.com</a>
								</p>
						</div>
                </div>
        
            </div>
            
        </div>


        <div class="copyright_part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="copyright_text">
                            <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Website made with <i class="ti-heart" aria-hidden="true"></i>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="footer_icon social_icon">
                            <ul class="list-unstyled">
                                {% comment %} <li><a href="#" class="single_social_icon"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="#" class="single_social_icon"><i class="fab fa-twitter"></i></a></li>
                                {% endcomment %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--::footer_part end::--> 

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
<title>Home - St Royal Stoi</title>
{% endblock css %}

{% block content %}


    <!-- banner part start-->
    <section class="banner_part">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <div class="banner_slider owl-carousel">
                        <div class="single_banner_slider">
                            <div class="row">
                                <div class="col-lg-5 col-md-8">
                                    <div class="banner_text">
                                        <div class="banner_text_iner">
                                            <h1>LIGHTING YOUR WORLD
                                                </h1>
                                            <p>Dealers in all kinds of electrical & Industrial materials.</p>
                                            <a href="{% url 'core:shop' %}" class="btn_3">buy now</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="banner_img d-none d-lg-block">
<div class="col-md-12">
    <img src="{% static 'img/banner_img.png' %}" alt="">
</div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="single_banner_slider">
                            <div class="row">
                                <div class="col-lg-5 col-md-8">
                                    <div class="banner_text">
                                        <div class="banner_text_iner">
                                            <h1>ENVIRONMENT FRIENDLY</h1>
                                            <p>Patronizing us is helping the Eco system cause here at STOI we pride ourselves to giving back to the environment</p>
                                            <a href="{% url 'core:shop' %}" class="btn_3">buy now</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="banner_img d-none d-lg-block">
                                  <div class="col-md-12">
                                    <img src="{% static 'img/banner_2.png' %}" class="img-fluid" alt="">
                                  </div>
                                </div>
                            </div>
                        </div>
                    
                        <!-- <div class="single_banner_slider">
                            <div class="row">
                                <div class="col-lg-5 col-md-8">
                                    <div class="banner_text">
                                        <div class="banner_text_iner">
                                            <h1>Cloth $ Wood Sofa</h1>
                                            <p>Incididunt ut labore et dolore magna aliqua quis ipsum
                                                suspendisse ultrices gravida. Risus commodo viverra</p>
                                            <a href="#" class="btn_2">buy now</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="banner_img d-none d-lg-block">
                                    <img src="img/banner_img.png" alt="">
                                </div>
                            </div>
                        </div> -->
                    </div>
                    <div class="slider-counter"></div>
                </div>
            </div>
        </div>
    </section>
    <!-- banner part start-->

{% include 'expert.html' %}

    <!-- upcoming_event part start-->

   	
    <div class="site-section about-section mt-5" id="about-section">
        <div class="container">
          <div class="row align-items-center mb-5 pb-5">
            <div class="col-lg-6 img-years mb-5 mb-lg-0">
              <img src="{% static 'img/deco.jpg' %}" alt="Image" class="img-fluid">
            </div>
            <div class="col-lg-6 ml-auto">
              <span class="sub-title">Durability Speaks</span>
              <h1 class="mb-4">Get the best experience and smile later
</h1>
              <p class="mb-4">
We keep a full line of long lasting stocked inventory and offer brand name qualities at the best possible price.
</p>
         
              <p><a href="{% url 'core:about' %}" class="btn_3">Read More</a></p>
            </div>
          </div>
  
          
        </div>
      </div>

      <div class="site-section about-section" id="about-section">
        <div class="container">
          <div class="row align-items-center mb-5 pb-5">
       
            <div class="col-lg-6 ml-auto">
              <span class="sub-title">Quote Me</span>
              <h1 class="mb-4">About Us</h1>
              <p class="mb-4">We serve you to the best of our ability bringing to you authentic products straight to your door step and give you authentic products at a cheaper rate with a guarantee you can trust</p>
         
              <p><a href="{% url 'core:contact' %}" class="btn_3 mb-2">get A Quote</a></p>
            </div>
            <div class="col-lg-6 img-years mb-5 mb-lg-0">
                <img src="{% static 'img/bul.jpg' %}" alt="Image" class="mt-2 img-fluid">
              </div>
          </div>
  
          
        </div>
      </div>


      {% include 'quote.html' %}

      <div class="site-section about-section mt-5" id="about-section">
        <div class="container">
          <div class="row align-items-center mb-5 pb-5">
            <div class="col-lg-6 img-years mb-5 mb-lg-0">
              <img src="{% static 'img/bulbs.jpg' %}" alt="Image" class="img-fluid">
            </div>
            <div class="col-lg-6 ml-auto">
              <span class="sub-title">Shop Now</span>
              <h1 class="mb-4">Shop With Us</h1>
              <p class="mb-4">We only sell Original products with the aim to please our customers and also use it in giving back to the community we serve the our community and make life better for our environment</p>
         
              <p><a href="{% url 'core:shop' %}" class="btn_3">Shop Now</a></p>
            </div>
          </div>
  
          
        </div>
      </div>





    <!--::subscribe_area part end::-->


    <!--::subscribe_area part end::-->
    {% include 'partners.html' %}

    <!-- subscribe_area part start-->
    <section class="subscribe_area section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <div class="subscribe_area_text text-center">
                        <h5 class="text-red">Join Our Newsletter</h5>
                        <h2>Subscribe to get Updated
                            with new offers</h2>
                     <form  method="POST">
                         {% csrf_token %}
                        <div class="input-group">
                            <input type="email" class="form-control" placeholder="enter email address"
                                aria-label="Recipient's username" aria-describedby="basic-addon2" name="email" id="email">
                            <div class="input-group-append">
                                <button type="submit" class="input-group-text btn_3" id="basic-addon2">subscribe now</button>
                            </div>
                        </div>
                     </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!--::subscribe_area part end::-->
 {% include 'selling.html' %}

{% endblock content %}

templates/quote.html
{% load static %}


   <!-- ======= Cta Section ======= -->
   <section id="cta" class="cta">
    <div class="container">

      <div class="row">
        <div class="col-lg-9 text-center text-lg-left">
          <h3> <span class="text-red">Your choice of design</span> is not restricted. </h3>
          <p> We don't stress our customers, hence we make sure our materials are very convenient, reliable and efficient.
  <br>We have more than enough designs for you to choose from.
            </p>
        </div>
        <div class="col-lg-3 cta-btn-container text-center">
          <a class=" btn_3" href="{% url 'core:contact' %}">get A Quote</a>
        </div>
      </div>

    </div>
  </section><!-- End Cta Section -->

templates/sale_template.html
{% load humanize %}

Hello, we have received an order from {{name}} {{name_2}},

We have received the order of {% for order_item in order.items.all %} 
{{ order_item.quantity }} x {{order_item.item.title }} {% endfor %} for ₦{{amount|intcomma}}..

The user, {{name}} {{name_2}} can be reached via {{address}} {{country}},{{state}} with the phpone number {{number}}

Do contact the user immediately.